config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#house'
  get 'home/gongjiindex' => 'home#gongjiindex'
  get 'home/gongjishow/:id' => 'home#gongjishow'
  get 'home/gongjiedit/:id' => 'home#gongjishow'
  get 'home/gongjiupdate/:id' => 'home#gongjishow'
  get 'home/gongjidestroy/:id' => 'home#gongjidestroy'
  post "home/gongjicreate" => 'home#gongjicreate'
  get 'home/refer' => 'home#refer'
  get 'home/gongji' => 'home#gongji'
  get 'home/clean' => 'home#clean'
  get 'home/wash' => 'home#wash'
  get 'home/birthday' => 'home#birthday'
  resources :posts , controller: 'home'









end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :set_post, only: [ :edit,:update,:destroy]
    
    def house
      
    end
    def gongji
    end
    
    def gongjiindex
      @post = Post.all
    end
    def gongjicreate
      @post = Post.new
      @post.title = params[:title]
      @post.content = params[:content]
      @post.save
      # redirect_to "/home/gongjishow/#{@post.id}"
      redirect_to "/home/gongjiindex"
    end
    
    def gongjishow
      @post = Post.find(params[:post_id])
    end
    
    def gongjiedit
      @post = Post.find(params[:post_id])
    end
    
    def gongjiupdate
      @post = Post.find(params[:post_id])
      @post.title = params[:title]
      @post.content = params[:content]
      @post.save
      redirect_to root_path
    end
    def gongjidestroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to "/home/gongjidex"
    end
    
    def index
     @title =  Post.pluck(:title)
    end
    
    def new
      @post = Post.new
    end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
   @post = Post.find(params[:id])
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:content)
  end
  
  def clean
  end
  
  def wash #빨래당번
  end
  
  def birthday
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_form.html.erb
<%= form_for @post do |f| %>
제목 : <%= f.text_field :title %></br>
내용 :<%= f.text_area :content %></br>
<%= f.submit '전송' %>
<%end%>

app/views/home/birthday.html.erb
	


<!DOCTYPE html><html lang='en' class=''>
<head><script src='//static.codepen.io/assets/editor/live/console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js'></script><script src='//static.codepen.io/assets/editor/live/css_live_reload_init-890dc39bb89183d4642d58b1ae5376a0193342f9aed88ea04330dc14c8d52f55.js'></script>
<meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="shortcut icon" type="image/x-icon" href="//static.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" /><link rel="mask-icon" type="" href="//static.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" /><link rel="canonical" href="https://codepen.io/rossdw/pen/XjmzAw" />

<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css'><link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'>
<style class="cp-pen-styles">.btn.btn-primary {

}</style></head><body>
 <!-- navigation bar -->

</div>
  <nav class="navbar-default">
    <div class="container-fluid">
<div class="outer">
 <div class="inner">
    <label><a href="/">Back </a></label>
  </div>
</div> 
      <a class="navbar-brand ml-auto"><i class="glyphicon glyphicon-bullhorn"></i> 생일을 부탁해 </a>

    </div>
  </nav>
  <br>
  <br>
  <br>
  <!-- main body of our application -->
  <div class="container" id="events">

    <!-- add an event form -->
    <div class="col-sm-6">
      <div class="panel panel-default">
          <div class="panel-heading">
  			<h3>생일 추가하기</h3>
			</div>
<div class="panel-body">

  <div class="form-group">
    <input class="form-control" placeholder="이름" v-model="event.name">
  </div>

  <div class="form-group">
    <textarea class="form-control" placeholder="특이 사항" v-model="event.description"></textarea>
  </div>

  <div class="form-group">
    <input type="date" class="form-control" placeholder="Date" v-model="event.date">
  </div>

  <button class="btn btn-primary" v-on:click="addEvent">저장하기</button>

</div>
      </div>
       
    </div>
   
    <!-- show the events -->

    <div class="col-sm-6">
			<button class="btn btn-primary" @click="order = order * -1">Reverse Order</button>
      <div class="list-group">

  <a href="#" class="list-group-item" v-for="event in events | orderBy 'date' order">
    <h4 class="list-group-item-heading">
      <i class="glyphicon glyphicon-bullhorn"></i> 
      {{ event.name }}
    </h4>

    <h5>
      <i class="glyphicon glyphicon-calendar" v-if="event.date">\ 
      {{ event.date }}</i>
    </h5>

    <p class="list-group-item-text" v-if="event.description">{{ event.description }}</p>

    <button class="btn btn-xs btn-danger" v-on:click="deleteEvent($index)">Delete</button>
  </a>

</div>

    </div>
  </div>

<script src='//static.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script><script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js'></script>
<script >// app js

new Vue({
  el: '#events',
  
  data: {
		order: 1,
	  event: { name: '', description: '', date: '' },
	  events: []
	},

	ready: function() {
		this.fetchEvents();
	},

	methods: {
  	fetchEvents: function() {
    	var events = [
				{
					id: 1,
					name: '아빠 생일',
					description: '아빠가 좋아하는 에버랜드 가기',
					date: '2018-09-12'
				},
				{
					id: 2,
					name: '엄마 생일',
					description: '엄마가 좋아하는 노래방 가기',
					date: '2018-05-11'
				},
				{
					id: 3,
					name: '첫 째 생일',
					description: '첫 째가 좋아하는 닭발 먹기',
					date: '2018-09-11'
				},
				{
					id: 4,
					name: '둘 째 생일',
					description: '둘 째가 좋아하는 공포영화 보러 가기',
					date: '2018-06-19'
				},

   	 ];

    	this.$set('events', events);
  	},

		addEvent: function() {
			if(this.event.name) {
				this.events.push(this.event);
				this.event = { name: '', description: '', date: '' };
			}
		},
		
		deleteEvent: function(index) {
			if (confirm('삭제 하시겠습니까?')) {
				this.events.splice(index,1);
			}
		}
	}
})
//# sourceURL=pen.js
</script>
</body></html>

app/views/home/clean.html.erb
<!DOCTYPE html>
  <nav class="navbar-default">
    <div class="container-fluid">
<div class="outer">
 <div class="inner">
    <label><a href="/">Back </a></label>
  </div>
</div> 
<html>
<head>
	<link rel="stylesheet" type="text/css" href="assets/css/clean.css">
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script type="text/javascript" src="ra.js"></script>
</head>

<style>
    @import url("https://fonts.googleapis.com/css?family=Roboto+Condensed");
* {
  box-sizing: border-box;
}

body {
  padding: 6.25em 1.5em 0;
  height: 100vh;
  text-align: center;
  background: whitesmoke;
}

body,
button {
  font-family: "Roboto Condensed", sans-serif;
  font-size: 1em;
  line-height: 1.4;
}
@media (min-width: 450px) {
  body,
  button {
    font-size: 1.125em;
  }
}

h2 {
  margin-bottom: 0.1875em;
  font-size: 1.5em;
  line-height: 1.2;
}
@media (min-width: 450px) {
  h2 {
    font-size: 2.25em;
  }
}

a {
  color: deepskyblue;
  text-decoration: none;
}
a:not(.btn):hover {
  color: #33ccff;
}

.btn {
  padding: 0.75em 2.25em;
  color: white;
  background-color: #33ccff;
  border: none;
  border-radius: 2px;
  cursor: pointer;
}
.btn:active {
  -webkit-transform: translateY(1px);
          transform: translateY(1px);
}
.btn:focus {
  outline-color: #33ccff;
}
.btn:hover {
  background-color: deepskyblue;
}

.btn-sm {
  padding: 0.375em 1.125em;
  font-size: 0.75em;
  letter-spacing: 0.01875em;
}

.container {
  overflow: hidden;
  margin: 1.5em auto 0;
  padding: 1.5em;
  width: 100%;
  max-width: 600px;
  text-align: center;
  background: white;
  border: 1px solid #e8e8e8;
  border-radius: 2px;
  box-shadow: rgba(0, 0, 0, 0.1) 0 3px 6px -3px;
}
.container p:not(:last-child) {
  margin-bottom: 0.9375em;
}

.loader {
  margin: auto;
  width: 40px;
  height: 40px;
  border: 6px solid transparent;
  border-top-color: deepskyblue;
  border-right-color: deepskyblue;
  border-bottom-color: deepskyblue;
  border-radius: 100%;
  -webkit-animation: spin 0.4s linear infinite;
          animation: spin 0.4s linear infinite;
}

@-webkit-keyframes spin {
  from {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }
  to {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

@keyframes spin {
  from {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
  }
  to {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}

</style>

<body>

<button class="btn" id="search-jobs" title="Search for a job on Codepen">오늘의 요리사는?:)</button>
<div class="container" id="job">
  <p>식사당번 정하기!</p>
</div>

<script>

	const url = 'https://codepen.io/jobs.json';
	const $searchBtn = $('#search-jobs');
	const $jobContainer = $('#job');

	$searchBtn.on('click', getJobs);

	function getJobs() {
	  $jobContainer.html('<div class="loader"/>');
	  
	  $.getJSON(url)
	    .done(data => {
	   //   const jobs = data.jobs;
	   //   const job = jobs[Math.floor(Math.random() * jobs.length)];
	      const rand = Math.floor(Math.random() * 4) + 1;
	      var arr = ['병우','민근','예랑','소정']
	      const jobHtml = `
	        <h2>
	          <img src="/KT${rand}.jpg">
	        </h2>
	        <p>${arr[rand-1]}</p>
	        `;

	      $jobContainer.html(jobHtml);
	      $searchBtn.text('다시!');
	  })
	    .fail(() => {
	      $jobContainer.html('<p>A job could not be fetched at this time</p>');
	    })
	          console.log(jobs);
	}
</script>



</body>
</html>

app/views/home/edit.html.erb
<%=render 'form'%>

app/views/home/gongji.html.erb
<style>
    @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,600,400italic);
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  -moz-font-smoothing: antialiased;
  -o-font-smoothing: antialiased;
  font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

body {
  font-family: "Roboto", Helvetica, Arial, sans-serif;
  font-weight: 100;
  font-size: 12px;
  line-height: 30px;
  color: #777;
  background: #4CAF50;
}

.container {
  max-width: 400px;
  width: 100%;
  margin: 0 auto;
  position: relative;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea,
#contact button[type="submit"] {
  font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
}

#contact {
  background: #F9F9F9;
  padding: 25px;
  margin: 150px 0;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

#contact h3 {
  display: block;
  font-size: 30px;
  font-weight: 300;
  margin-bottom: 10px;
}

#contact h4 {
  margin: 5px 0 15px;
  display: block;
  font-size: 13px;
  font-weight: 400;
}

fieldset {
  border: medium none !important;
  margin: 0 0 10px;
  min-width: 100%;
  padding: 0;
  width: 100%;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea {
  width: 100%;
  border: 1px solid #ccc;
  background: #FFF;
  margin: 0 0 5px;
  padding: 10px;
}

#contact input[type="text"]:hover,
#contact input[type="email"]:hover,
#contact input[type="tel"]:hover,
#contact input[type="url"]:hover,
#contact textarea:hover {
  -webkit-transition: border-color 0.3s ease-in-out;
  -moz-transition: border-color 0.3s ease-in-out;
  transition: border-color 0.3s ease-in-out;
  border: 1px solid #aaa;
}

#contact textarea {
  height: 100px;
  max-width: 100%;
  resize: none;
}

#contact button[type="submit"] {
  cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 0 0 5px;
  padding: 10px;
  font-size: 15px;
}

#contact button[type="submit"]:hover {
  background: #43A047;
  -webkit-transition: background 0.3s ease-in-out;
  -moz-transition: background 0.3s ease-in-out;
  transition: background-color 0.3s ease-in-out;
}

#contact button[type="submit"]:active {
  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
}

.copyright {
  text-align: center;
}

#contact input:focus,
#contact textarea:focus {
  outline: 0;
  border: 1px solid #aaa;
}

::-webkit-input-placeholder {
  color: #888;
}

:-moz-placeholder {
  color: #888;
}

::-moz-placeholder {
  color: #888;
}

:-ms-input-placeholder {
  color: #888;
}
</style>
<div class="container">  
  <form id="contact" action="/home/gongjicreate" method="post">
    <h3>공지사항</h3>
    <h4></h4>
    <fieldset>
      <input placeholder="제목" name="id"type="text" tabindex="1" required autofocus>
    </fieldset>
    <fieldset>
      <textarea placeholder="내용" name="content" tabindex="5" required></textarea>
    </fieldset>
    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>
    <p class="copyright">Designed by <a href="https://colorlib.com" target="_blank" title="Colorlib">Colorlib</a></p>
  </form>
</div>

app/views/home/gongjiedit.html.erb
<style>
    @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,600,400italic);
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  -moz-font-smoothing: antialiased;
  -o-font-smoothing: antialiased;
  font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

body {
  font-family: "Roboto", Helvetica, Arial, sans-serif;
  font-weight: 100;
  font-size: 12px;
  line-height: 30px;
  color: #777;
  background: #4CAF50;
}

.container {
  max-width: 400px;
  width: 100%;
  margin: 0 auto;
  position: relative;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea,
#contact button[type="submit"] {
  font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
}

#contact {
  background: #F9F9F9;
  padding: 25px;
  margin: 150px 0;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

#contact h3 {
  display: block;
  font-size: 30px;
  font-weight: 300;
  margin-bottom: 10px;
}

#contact h4 {
  margin: 5px 0 15px;
  display: block;
  font-size: 13px;
  font-weight: 400;
}

fieldset {
  border: medium none !important;
  margin: 0 0 10px;
  min-width: 100%;
  padding: 0;
  width: 100%;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea {
  width: 100%;
  border: 1px solid #ccc;
  background: #FFF;
  margin: 0 0 5px;
  padding: 10px;
}

#contact input[type="text"]:hover,
#contact input[type="email"]:hover,
#contact input[type="tel"]:hover,
#contact input[type="url"]:hover,
#contact textarea:hover {
  -webkit-transition: border-color 0.3s ease-in-out;
  -moz-transition: border-color 0.3s ease-in-out;
  transition: border-color 0.3s ease-in-out;
  border: 1px solid #aaa;
}

#contact textarea {
  height: 100px;
  max-width: 100%;
  resize: none;
}

#contact button[type="submit"] {
  cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 0 0 5px;
  padding: 10px;
  font-size: 15px;
}

#contact button[type="submit"]:hover {
  background: #43A047;
  -webkit-transition: background 0.3s ease-in-out;
  -moz-transition: background 0.3s ease-in-out;
  transition: background-color 0.3s ease-in-out;
}

#contact button[type="submit"]:active {
  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
}

.copyright {
  text-align: center;
}

#contact input:focus,
#contact textarea:focus {
  outline: 0;
  border: 1px solid #aaa;
}

::-webkit-input-placeholder {
  color: #888;
}

:-moz-placeholder {
  color: #888;
}

::-moz-placeholder {
  color: #888;
}

:-ms-input-placeholder {
  color: #888;
}
</style>
<div class="container">  
  <form id="contact" action="/home/gongjicreate" method="get">
    <h3>공지사항</h3>
    <h4></h4>
    <fieldset>
      <input placeholder="제목" name="id" value="<%=@post.title%>"type="text" tabindex="1" required autofocus>
    </fieldset>
    <fieldset>
      <textarea placeholder="내용" name="content" value="<%=@post.content%>"tabindex="5" required></textarea>
    </fieldset>
    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
    </fieldset>
    <p class="copyright">Designed by <a href="https://colorlib.com" target="_blank" title="Colorlib">Colorlib</a></p>
  </form>
</div>

app/views/home/gongjiindex.html.erb
<style>
    @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,600,400italic);
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  -moz-font-smoothing: antialiased;
  -o-font-smoothing: antialiased;
  font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

body {
  font-family: "Roboto", Helvetica, Arial, sans-serif;
  font-weight: 100;
  font-size: 12px;
  line-height: 30px;
  color: #777;
  background: #4CAF50;
}

.container {
  max-width: 400px;
  width: 100%;
  margin: 0 auto;
  position: relative;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea,
#contact button[type="submit"] {
  font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
}

#contact {
  background: #F9F9F9;
  padding: 25px;
  margin: 150px 0;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}

#contact h3 {
  display: block;
  font-size: 30px;
  font-weight: 300;
  margin-bottom: 10px;
}

#contact h4 {
  margin: 5px 0 15px;
  display: block;
  font-size: 13px;
  font-weight: 400;
}

fieldset {
  border: medium none !important;
  margin: 0 0 10px;
  min-width: 100%;
  padding: 0;
  width: 100%;
}

#contact input[type="text"],
#contact input[type="email"],
#contact input[type="tel"],
#contact input[type="url"],
#contact textarea {
  width: 100%;
  border: 1px solid #ccc;
  background: #FFF;
  margin: 0 0 5px;
  padding: 10px;
}

#contact input[type="text"]:hover,
#contact input[type="email"]:hover,
#contact input[type="tel"]:hover,
#contact input[type="url"]:hover,
#contact textarea:hover {
  -webkit-transition: border-color 0.3s ease-in-out;
  -moz-transition: border-color 0.3s ease-in-out;
  transition: border-color 0.3s ease-in-out;
  border: 1px solid #aaa;
}

#contact textarea {
  height: 100px;
  max-width: 100%;
  resize: none;
}

#contact button[type="submit"] {
  cursor: pointer;
  width: 100%;
  border: none;
  background: #4CAF50;
  color: #FFF;
  margin: 0 0 5px;
  padding: 10px;
  font-size: 15px;
}

#contact button[type="submit"]:hover {
  background: #43A047;
  -webkit-transition: background 0.3s ease-in-out;
  -moz-transition: background 0.3s ease-in-out;
  transition: background-color 0.3s ease-in-out;
}

#contact button[type="submit"]:active {
  box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
}

.copyright {
  text-align: center;
}

#contact input:focus,
#contact textarea:focus {
  outline: 0;
  border: 1px solid #aaa;
}

::-webkit-input-placeholder {
  color: #888;
}

:-moz-placeholder {
  color: #888;
}

::-moz-placeholder {
  color: #888;
}

:-ms-input-placeholder {
  color: #888;
}
</style>
<div class="container">  
  <form id="contact" action="/home/gongjicreate" method="get">
    <h3>공지사항</h3>
    <%@post.each do |t| %>
    제목 : <%=t.title%><br>
    내용 : <%=t.content%><br>
   <button name="submit" type="submit "><a href="/home/gongjishow/<%=t.id%>">공지 보기</a></button>
   <button name="submit" type="submit"><a href="/home/gongjiedit/<%=t.id%>">수정</a></button>
   <button name="submit" type="submit"><a href="/home/gongjidestroy/<%=t.id%>">삭제</a></button>
    -------------------------------------------------------------------<br>
    <%end%>
    <button name="submit" type="submit"><a href="/">메인화면</a></button>
  </form>
</div>

app/views/home/house.html.erb
<style>.speech-bubble {font-style:italic;}</style>
<div class="container">
  <div class='speech-bubble'>살림을 부탁해<br></div>
						<div class="navi">
				<ul>
					<li>
					  
						<a class="mens active ml-auto" href="/home/refer">냉장고 관리</a>
					</li>
					<li>
						<a class="womens" href="/home/clean">당번 정하기</a>
					</li>

					<li>
						<a class="kids" href="/home/birthday">가족생일</a>
					</li>
					<li class="notifs">
						<a data-toggle="dropdown"  aria-expanded="false" class="notifications">가족공지&nbsp;</a>
							<div class="dropdown-menu" role="menu">
							    	<%=link_to '메모', posts_path %>
							    	<%=link_to '공지작성', home_gongji_path%>
							</div>
						</li>
					</ul>

</div>
<div class='road'>
</div>
<div class='wrap'>
  <div class='cube'>
    <div class='face'>
      <div class='topdoor'></div>
      <div class='bottomdoor'>
        <div class='smile'></div>
      </div>
    </div>
    <div class='face'></div>
    <div class='face'></div>
    <div class='face'></div>
    <div class='face'></div>
    <div class='face'></div>
  </div>
  <div class='plug'></div>
  <div class='legs'>
    <div class='lower'></div>
  </div>
  <div class='legs left'>
    <div class='lower'></div>
  </div>

app/views/home/new.html.erb
<h2>글쓰기</h2>
<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>